# Generated by Django 4.1.2 on 2022-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_alter_employee_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="NullBlankDemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blank", models.IntegerField(blank=True)),
                ("null", models.IntegerField(null=True)),
                ("blank_null", models.IntegerField(blank=True, null=True)),
                ("default", models.IntegerField()),
            ],
        ),
    ]
