# Generated by Django 4.1.2 on 2022-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_nullblankdemo"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_full_time",
            field=models.BooleanField(null=True),
        ),
    ]
