# Generated by Django 4.1.2 on 2022-10-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_alter_employee_projects_employeesprojects_accesscard"),
    ]

    operations = [
        migrations.RemoveField(model_name="accesscard", name="id",),
        migrations.AlterField(
            model_name="accesscard",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="web.employee",
            ),
        ),
    ]
