# Generated by Django 4.1.2 on 2022-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee", name="years_of_experience_positive",
        ),
    ]
