# Generated by Django 4.1.2 on 2022-10-29 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_remove_employee_years_of_experience_positive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee", options={"ordering": ("years_of_experience", "-age")},
        ),
        migrations.AddField(
            model_name="department",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
