# Generated by Django 4.1.2 on 2022-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
