# Generated by Django 4.1.2 on 2022-11-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_department_slug"),
    ]

    operations = []
