# Generated by Django 4.1.2 on 2022-10-30 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCollectionWeb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(
                default=1,
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="type",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
