# Generated by Django 4.1.2 on 2022-10-30 14:49

import CarCollection.CarCollectionWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCollectionWeb", "0002_car_model_car_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="model",),
        migrations.AlterField(
            model_name="car",
            name="type",
            field=models.CharField(
                choices=[
                    ("Sports Car", "Sports Car"),
                    ("Pickup", "Pickup"),
                    ("Crossover", "Crossover"),
                    ("Minibus", "Minibus"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                max_length=10,
                validators=[
                    CarCollection.CarCollectionWeb.models.validate_username_min_length
                ],
            ),
        ),
    ]
