# Generated by Django 4.1.2 on 2022-10-30 14:50

import CarCollection.CarCollectionWeb.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarCollectionWeb", "0003_remove_car_model_alter_car_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(
                default=1,
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.IntegerField(
                default=1,
                validators=[CarCollection.CarCollectionWeb.models.validate_years_range],
            ),
            preserve_default=False,
        ),
    ]
